
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dogram?sueSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: sample
    password: 12345678
  jpa:
    show-sql: true

server:
  port: 8000